services:
  - type: web
    name: parthtraderalerts-chartink-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_IDS
        sync: false

      - key: WEBHOOK_BASE_URL
        sync: false

      - key: WEBHOOK_SECRET
        sync: false

      - key: LOG_LEVEL
        value: INFO
